universal_map:
  default_mode: grid
  default_fog: true

  shortcuts:
    mp: map
    mcreate: map/create
    mview: map/view
    mtoken: map/addtoken
    mmove: map/move
    mobj: map/addobject
    mhide: map/hide
    mreveal: map/reveal
    mdel: map/delete
    muninstall: map/uninstall
